services:
  - type: web
    name: doc-validation-agent
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install pipenv
      pipenv install --deploy --system
    startCommand: python app/frontend/gradio_interface.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_URL
        sync: false # This will be set in Render dashboard
      - key: PIPENV_VENV_IN_PROJECT
        value: "1"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "7860"
