services:
  - type: web
    name: doc-validation-agent
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install pipenv
      pipenv --python 3.9
      pipenv lock
      pipenv install --deploy --system
    startCommand: |
      cd /opt/render/project/src
      python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: API_URL
        sync: false # This will be set in Render dashboard
      - key: PIPENV_VENV_IN_PROJECT
        value: "1"
      - key: HOST
        value: "0.0.0.0"
      - key: PORT
        value: "8000"
      - key: GEMINI_API_KEY
        sync: false # This will be set in Render dashboard
    buildFilter:
      paths:
        - app/**
        - Pipfile
        - Pipfile.lock
        - render.yaml
        - run.py
        - test_api.py
        - mvp_plan.md
        - readme.md
